backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

site_url: "https://harblo.netlify.app"
root_url: "/admin/"
publish_mode: editorial_workflow


collections:
  - name: "rocniky"
    label: "Ročníky závodů"
    folder: "src/years"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Název", name: "title", widget: "string" }
      - { label: "Rok", name: "year", widget: "number" }
      - { label: "Popis", name: "body", widget: "markdown" }

      - label: "Odkazy na výsledky"
        name: "vysledky"
        widget: "list"
        summary: "{{label}}"
        fields:
          - { label: "Kategorie", name: "label", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }

      - label: "Galerie"
        name: "gallery"
        widget: "list"
        summary: "{{image}}"
        fields:
          - { label: "Od-Koho", name: "from", widget: "string" }
          - { label: "Obrázek", name: "image", widget: "image" }
          - { label: "Odkaz na galerii", name: "link", widget: "string" }

      - { label: "Video ročníku", name: "video", widget: "string" }