backend:
  name: github
  repo: lukasvedral/hb
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"


site_url: "https://harblo.netlify.app"
root_url: "/admin/"
publish_mode: editorial_workflow


collections:
  - name: "years"
    label: "Ročníky"
    folder: "src/years"
    create: true
    slug: "{{year}}-{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Year", name: "year", widget: "number" }
      - { label: "Body", name: "body", widget: "text" }
      - label: "Vysledky"
        name: "vysledky"
        widget: "list"
        fields:
          - { label: "Label", name: "label", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }
      - label: "Gallery"
        name: "gallery"
        widget: "list"
        fields:
          - { label: "From", name: "from", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Link", name: "link", widget: "string" }
      - { label: "Video", name: "video", widget: "string" }